<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User Name_idcs-signin-basic-signin-fo_93898c</name>
   <tag></tag>
   <elementGuidId>5147a2f9-b18a-45af-b2eb-387376e1f6a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idcs-signin-basic-signin-form-username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#idcs-signin-basic-signin-form-username</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60c83101-1347-4796-bd85-2c03bb1484f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idcs-signin-basic-signin-form-username</value>
      <webElementGuid>c7c67fc1-c403-48d0-8288-66d9c7e8bf2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idcs-placeholder-translation-id</name>
      <type>Main</type>
      <value>idcs-username-placeholder</value>
      <webElementGuid>ed48b4ea-fdc7-4b5d-be01-789743ea1213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8cbc0181-7826-4f17-97eb-35fb80f56d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oj-sm-12 oj-form-control oj-inputtext-nocomp</value>
      <webElementGuid>27792184-a8cb-4b2f-a3d4-9da498d3cf37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>:class</name>
      <type>Main</type>
      <value>[[{'idcs-signin-rw-floating-input': isOracleEmployeeRedwood}]]</value>
      <webElementGuid>4918fdcf-a02f-49d5-b1bc-9d569e6ca33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>4329f2ae-db1c-4a70-a208-c7f15ec3108b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d782e6d9-a5f9-4275-a432-26ca905ae185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f16df83f-f8d9-4711-ab1e-50804df30432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>:placeholder</name>
      <type>Main</type>
      <value>[[bundle('signin.usernamePlaceHolder')]]</value>
      <webElementGuid>604e9550-37bd-4224-b3a3-3d842328d326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>:disabled</name>
      <type>Main</type>
      <value>[[$params.disableInput]]</value>
      <webElementGuid>055e8841-cbd1-4941-b688-0a275f142824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: username</value>
      <webElementGuid>7707f743-b41e-492f-844d-c96e334560b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-idcs-enable-right-click</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>48967169-62a7-4cb8-8874-2ba87ca6b6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User name or email</value>
      <webElementGuid>f1c99b8c-e4cd-48ca-9f4e-65893ae572cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idcs-signin-basic-signin-form-username&quot;)</value>
      <webElementGuid>d2fdf631-ed67-48d6-a8e1-0cd42fec7ac9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idcs-signin-basic-signin-form-username']</value>
      <webElementGuid>8687a5a9-be90-4ce4-be96-09f9df039c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='idcs-app-shell-signin-background']/div/div[2]/div/div/oj-module/div/oj-module/div/div/div/div/div/input</value>
      <webElementGuid>ec78b77c-3976-482a-9b44-3386f8217257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>dfe2be46-7d51-4c7c-a702-3fd65e34e7c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'idcs-signin-basic-signin-form-username' and @type = 'text' and @placeholder = 'User name or email']</value>
      <webElementGuid>3d2ca8df-3788-4e72-a7a7-055db3d8c4df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
