<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_Browser not supported_main</name>
   <tag></tag>
   <elementGuidId>c3d38abd-4c94-4efb-b0df-92ec309cf7b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='main']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;main&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>a1cf0a16-ece4-4f9e-a659-c0f30404e7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>f93e96ce-55d8-49c9-83ab-dd87bf138274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>cisMain.jsp?debug=true&amp;language=ENG</value>
      <webElementGuid>66a92d33-567b-4db7-8dc9-10bc7da76df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>87f6edeb-8d36-4c5e-95cb-42dffba99253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Main Frame</value>
      <webElementGuid>a990c7bd-2c2b-4a2b-b4bb-093716437271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>a9ac2188-fc02-43f4-a8aa-a47a2cdcf75b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='main']</value>
      <webElementGuid>efbd33ec-558a-40d7-877d-4c788a5531ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame</value>
      <webElementGuid>acf097f4-75c0-4d7f-bb83-bec0095fd85f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@name = 'main' and @src = 'cisMain.jsp?debug=true&amp;language=ENG' and @title = 'Main Frame']</value>
      <webElementGuid>2d609c35-f755-4b89-a300-468e1512a25f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
