<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Customer Cloud Service_visualUserPage</name>
   <tag></tag>
   <elementGuidId>ead93144-5383-4884-9287-662c6db1b7b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='visualUserPage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#visualUserPage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>0f3d1fa7-4337-4200-899b-70ee779ec416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visualUserPage</value>
      <webElementGuid>3602500b-8e31-4c86-aa2a-27721a9aceaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>visualUserPage</value>
      <webElementGuid>06f712d5-34a2-4c3b-aaf6-e63dc83b876b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Main Frame - New</value>
      <webElementGuid>fc4d6f9b-1598-4813-9f78-8dcc237b4173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>slp.jsp?slp=true&amp;dynamicJS=false&amp;debug=true</value>
      <webElementGuid>63998b4d-26eb-4890-8c9f-bfa1a5656330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>6ab5d4f8-676c-4804-b0de-f9e3738abc79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visualUserPage&quot;)</value>
      <webElementGuid>f10bf915-f6a7-46a5-94e1-6a12a80c312f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_User/frame_Browser not supported_main</value>
      <webElementGuid>7125c6ca-c0d9-4fc2-a391-d5b8b14adba8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='visualUserPage']</value>
      <webElementGuid>402da86d-4d09-405f-ac4c-b901a57739fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='visualUserPageContainer']/iframe</value>
      <webElementGuid>a3c960b0-70fc-4b41-bec3-2493c771fc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Cloud Service'])[1]/preceding::iframe[1]</value>
      <webElementGuid>eb953dde-112c-48ae-bd18-9e448ea4b366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f7cd506e-d594-48ef-9ef3-b67b347d0c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'visualUserPage' and @name = 'visualUserPage' and @title = 'Main Frame - New' and @src = 'slp.jsp?slp=true&amp;dynamicJS=false&amp;debug=true']</value>
      <webElementGuid>ef5fc0ae-b21e-4946-b00c-c328c8c78986</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
